#!/bin/bash

set -e

if [ -z "$1" ]; then 
  echo "Please provide update type: patch, minor major"
  exit 1;
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "Please ensure your git folder is clean";
  exit 1;
fi

yarn test
yarn build
npm version $1
git push --tags && git push
cp README.md dist
cp logo.png dist
cp package.json dist
cd dist
npm publish $2

