#!/bin/bash

set -e

# Save first arg to VERSION
VERSION=$1

# Move arg pointer
shift

# Rest of the args are --tag foo
TAGS=$@

if [ -z "$VERSION" ]; then 
  echo "Please provide update type: patch, minor major"
  exit 1;
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "Please ensure your git folder is clean";
  exit 1;
fi

if [ ! -z "$TAGS" ]; then 
  echo "This will use the tags: $TAGS"
  read
fi

yarn test
yarn build
npm version $VERSION
git push --tags && git push
cp README.md dist
cp logo.png dist
cp package.json dist
cd dist
npm publish $TAGS

